clear all; close all; clc;

cses = { ...
    AlphaShapeCompactor,    '\alpha-shape'; ...
    GMMDensitySampler,      'GMM'; ...
    KNNDensitySampler,      'kNN'; ...
    ParzenWindowSampler,    'Parzen Window' ...
};

datasets = { ...
    @gen_circle, {}; ...
    @gen_donut, {}; ...
    @gen_legs, {}; ...
    @gen_spiral, {}; ...
};

compare_cse_stationary_datasets(datasets, cses);