clear all; close all; clc;

cses = {                        ...
    AlphaShapeCompactor(        ...
        struct('alpha', .1)      ...
    ), '\alpha-shape';          ...
    GMMDensitySampler, 'GMM';   ...
    KNNDensitySampler(          ...
        struct('k', 50)         ...
    ), 'kNN';                   ...
    ParzenWindowSampler(        ...
        struct('sigma', 1)      ...
    ), 'Parzen Window'          ...
};

datasets = {                ...
    @gen_circle, {};        ...
    @gen_donut, {};         ...
    @gen_legs, {1000, 5};   ...
    @gen_spiral, {};        ...
};

compare_cse_stationary_datasets(datasets, cses);