clear_except_breakpoints; close all; clc;

cses = {                        ...
    AlphaShapeCompactor(        ...
        struct('alpha', .04)     ...
    ), '\alpha-shape';          ...
    GMMDensitySampler, 'GMM';   ...
    KNNDensitySampler(          ...
        struct('k', 50)         ...
    ), 'kNN';                   ...
    ParzenWindowSampler(        ...
        struct('sigma', 1)      ...
    ), 'Parzen Window'          ...
};

datasets = {                                 ...
    @gen_circle,    {},         'gaussian';  ...
    @gen_donut,     {},         'donut';     ...
    @gen_legs,      {1000, 5},  'star';      ...
    @gen_spiral,    {},         'spiral'     ...
};

compare_cse_stationary_datasets(datasets, cses);